### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by inn0minatus** [orling/Poppy#2]
Could you please clarify the situation with Windows support implementing?
Your library is great and very useful for any complex system, I'll be happy to use it.
Thanks in advance.

**Comment by orling** [comment]
Hey, thanks for your interest! To port to Windows, you'll need to implement the function CurrentTime to return the number of milliseconds passed since some fixed point in time, like the start of the epoch (1970) or the application start time. There is a TODO comment there with a link to another lib that may help. 

If you intend to use Poppy only for debugging, not performance measurement, it should work straight away on Windows as it is - just delete everything in CurrentTime and make it return 0 so it compiles properly.

**Comment by orling** [comment]
Neovet, did you manage to port the project to Windows? I just thought that some of the used compiler macros may need porting too, as I'm not sure if they are exactly the same in the VS compiler. Namely:
__FUNCTION__
__LINE__
__FILE__
__COUNTER__
